### ISSUE TITLE
You do not a new board after round finished

### ISSUE THREAD

**Issue by Hoymm** [KrzysztofDzioba/OX#31]
You do not a new board after round finished and I dont know how the board looks like when round finished, I see only info round finished

 Creating new board.
 0 | 1 | 2 | 3 | 4 | 5 |
 1 |   |   |   |   |   |
 2 |   |   |   |   |   |
 3 |   |   |   |   |   |
 4 |   |   |   |   |   |
 5 |   |   |   |   |   |

Player afd (X). Please make your move.
1 1
 0 | 1 | 2 | 3 | 4 | 5 |
 1 | X |   |   |   |   |
 2 |   |   |   |   |   |
 3 |   |   |   |   |   |
 4 |   |   |   |   |   |
 5 |   |   |   |   |   |

Player asdf (O). Please make your move.
1 2
 0 | 1 | 2 | 3 | 4 | 5 |
 1 | X | O |   |   |   |
 2 |   |   |   |   |   |
 3 |   |   |   |   |   |
 4 |   |   |   |   |   |
 5 |   |   |   |   |   |

Player afd (X). Please make your move.
3 1
 0 | 1 | 2 | 3 | 4 | 5 |
 1 | X | O |   |   |   |
 2 |   |   |   |   |   |
 3 | X |   |   |   |   |
 4 |   |   |   |   |   |
 5 |   |   |   |   |   |

Player asdf (O). Please make your move.
2 2
 0 | 1 | 2 | 3 | 4 | 5 |
 1 | X | O |   |   |   |
 2 |   | O |   |   |   |
 3 | X |   |   |   |   |
 4 |   |   |   |   |   |
 5 |   |   |   |   |   |

Player afd (X). Please make your move.
4 1
 0 | 1 | 2 | 3 | 4 | 5 |
 1 | X | O |   |   |   |
 2 |   | O |   |   |   |
 3 | X |   |   |   |   |
 4 | X |   |   |   |   |
 5 |   |   |   |   |   |

Player asdf (O). Please make your move.
3 2
Congratulations player asdf (O)! You won this game. 3 points are going to your account.
Results: 
Player asdf (O): 6 points. Player afd (X): 0 points.

**Comment by KrzysztofDzioba** [comment]
fixed
