### ISSUE TITLE
Not need to pass a argument here

### ISSUE THREAD

**Issue by Hoymm** [KrzysztofDzioba/OX#39]
https://github.com/KrzysztofDzioba/OX/blob/f851d4d2b3c5af4af9ce4c089545b62b9125b305/src/main/java/edu/dzioba/SetUpState.java#L26

Inside a .getWinningNumber(...) you also have access to new InputValidator(new InputConverter()), so you don't have to pass it as an argument.

**Comment by KrzysztofDzioba** [comment]
fixed
