### ISSUE TITLE
Useless constructor argument

### ISSUE THREAD

**Issue by Hoymm** [KrzysztofDzioba/OX#40]
https://github.com/KrzysztofDzioba/OX/blob/f851d4d2b3c5af4af9ce4c089545b62b9125b305/src/main/java/edu/dzioba/InputValidator.java#L7

You always invoke constructor by new `InputValidator(new InputConverter())` , you have an access to  InputConverter() inside InputValidator class. That means you don't need that constructor in InputValidator class, you can initialize that variable just where you declare it:

```
public class InputValidator {

    private InputConverter converter = new InputConverter();

    public InputValidator() {
    }

```

**Comment by KrzysztofDzioba** [comment]
fixed
