### ISSUE TITLE
Remove these if's

### ISSUE THREAD

**Issue by Hoymm** [KrzysztofDzioba/OX#41]
https://github.com/KrzysztofDzioba/OX/blob/d3c29ba6682076a239a527ab0a2fd2b24ef6c0ef/src/main/java/edu/dzioba/Sign.java#L7

```
public enum Sign {
    X,
    O;

    public static Sign getOppositeSign(Sign winningSign) {
        if(winningSign == Sign.X)
            return Sign.O;
        else
            return Sign.X;
    }
}
```

make getOppositeSign abstract, and implemet it inside X and O
Sign.O getOppositeSign just return X; 
Sign.O. getOppositeSign just return O;

and you have no if's in your code

**Comment by KrzysztofDzioba** [comment]
fixed
